#!/usr/bin/env bash

# Update the package list to get the latest information about available packages
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Create an index.html file with the "Hello World!" content in the default root directory
echo "Hello World!" | sudo tee /var/www/html/index.html

# Restart Nginx without using systemctl
sudo service nginx restart
