#!/usr/bin/env bash
# Update the package list to get the latest information about available packages
apt-get -y update
apt-get -y install nginx
echo "Hello World" > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.linkedin.com/in/niyiolagbegi permanent;' /etc/nginx/sites-available/default
service nginx start
