#!/usr/bin/env bash
# Update the package list to get the latest information about available packages
sudo apt update

# Install Nginx if it's not already installed
if ! dpkg -l | grep -q nginx; then
    sudo apt install -y nginx
fi

# Create an Nginx server block configuration file for the redirection
echo "
server {
    listen 80;
    server_name niyioo.tech;

    location /redirect_me {
        return 301 https://linkedin.com/in/niyiolagbegi;
    }

    location / {
        # Your regular website configuration here
    }
}
" | sudo tee /etc/nginx/sites-available/redirect_me

# Create a symbolic link to enable the server block
sudo ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Remove the default Nginx server block (if desired)
# sudo rm /etc/nginx/sites-enabled/default

# Test Nginx configuration
sudo nginx -t

# If the configuration test is successful, reload Nginx to apply changes
if [ $? -eq 0 ]; then
    sudo service nginx reload
    echo "Nginx configuration reloaded successfully."
else
    echo "Nginx configuration test failed. No changes were applied."
fi

