#!/usr/bin/env bash
# This script configures Nginx to add a custom HTTP response header.
if ! dpkg -l | grep -q "nginx"; then
  sudo apt-get update
  sudo apt-get install -y nginx
fi
echo 'add_header X-Served-By $hostname;' | sudo tee /etc/nginx/conf.d/custom-header.conf
sudo nginx -t
sudo systemctl reload nginx
