#!/usr/bin/env bash
# This script installs and configures HAProxy on an Ubuntu server
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.0
apt-get -y update
apt-get -y install haproxy=2.0.\*
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 348963-web-01 54.236.30.173:80 check\n\tserver 348963-web-02 100.26.56.25:80 check" >> /etc/haproxy/haproxy.cfg
service haproxy restart
