#!/usr/bin/env bash
# This script generates a MySQL dump, compresses it into a tar.gz archive, and follows specific naming requirements.
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -cvzf "$(date +%d-%m-%Y)".tar.gz backup.sql
