#!/usr/bin/env bash
# This script configures Nginx to listen on port 80 of all active IPv4 IPs.
apt-get update
apt-get install -y nginx
nginx_config_file="/etc/nginx/sites-available/default"
service nginx restart
