#!/usr/bin/env bash
# Configure Nginx to listen on port 80 for all active IPv4 IPs.
sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
service nginx restart
kill -9 "$(cat /run/nginx.pid)"
