#!/usr/bin/env bash
# Bash script to display "To infinity and beyond" indefinitely

# Function to handle the SIGINT signal (Ctrl+C)
function sigint_handler() {
	echo "Received SIGINT signal. Stopping the loop."
		exit 0
}

# Register SIGINT signal handler
trap sigint_handler SIGINT

# Infinite loop with a sleep of 2 seconds between iterations
while true; do
echo "To infinity and beyond"
sleep 2
done
