#!/usr/bin/env bash
# This script displays a made-up story based on the content of the file /etc/passwd using the while loop and IFS.

file="/etc/passwd"

# Check if the file exists
if [ -e "$file" ]; then
    # Read the file line by line using while loop and IFS
    while IFS=: read -r username _ userid groupid _ homedir shell; do
        echo "The user $username is part of the $groupid gang,"
        echo "lives in $homedir and rides $shell."
        echo "USER ID's place is protected by the passcode PASSWORD,"
        echo "more info about the user here: USER ID INFO"
        echo "------------------"
    done < "$file"
else
    echo "File /etc/passwd does not exist."
fi
