#!/usr/bin/env bash
# This script tells a made-up story based on the content of the file /etc/passwd using a while loop and IFS.

file="/etc/passwd"

# Check if the file exists
if [ -e "$file" ]; then
	# Read the file line by line using while loop and IFS
	while IFS=: read -r username _ userid groupid info homedir shell; do
		echo "The user $username is part of the $groupid gang,"
		echo "lives in $homedir and rides $shell. $userid's place is protected by the passcode x,"
		echo "more info about the user here: $info"
		echo "------------------"
	done < "$file"
else
	echo "File $file does not exist."
fi
