#!/usr/bin/env bash
# Script: configure_ubuntu_server.sh
# Description: Configure Ubuntu server to map localhost and facebook.com to specific IP addresses.
cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
